In [ ]:
Q1.  
   - A database is a structured collection of data that is organized and stored electronically. It allows for efficient retrieval, insertion, and manipulation of data.
   - SQL (Structured Query Language) databases are relational databases that use structured query language to define and manipulate the data. They organize data into tables, which have predefined schemas.
   - NoSQL databases, on the other hand, are non-relational databases that do not require a fixed schema. They are more flexible and can handle unstructured data. NoSQL databases use different data models such as key-value pairs, document stores, column-oriented, or graph databases.

Q2. 
   - DDL (Data Definition Language) is a subset of SQL used to define and modify the structure of database objects.
   - **CREATE** is used to create new database objects like tables, indexes, or views.
   - **DROP** is used to delete existing database objects.
   - **ALTER** is used to modify the structure of existing database objects.
   - **TRUNCATE** is used to remove all records from a table without removing the table structure.
   Example: 
   ```sql
   CREATE TABLE employees (
       id INT PRIMARY KEY,
       name VARCHAR(50),
       age INT
   );
   ```

Q3. 
   - DML (Data Manipulation Language) is used to manipulate data within database objects.
   - **INSERT** is used to add new records to a table.
   - **UPDATE** is used to modify existing records in a table.
   - **DELETE** is used to remove existing records from a table.
   Example:
   ```sql
   INSERT INTO employees (id, name, age) VALUES (1, 'John', 30);
   UPDATE employees SET age = 31 WHERE name = 'John';
   DELETE FROM employees WHERE name = 'John';
   ```

Q4. **What is DQL? Explain SELECT with an example:**
   - DQL (Data Query Language) is used to retrieve data from the database.
   - **SELECT** statement is used to retrieve data from one or more tables.
   Example:
   ```sql
   SELECT * FROM employees WHERE age > 30;
   ```

Q5. 
   - **Primary Key**: A primary key is a column or a set of columns that uniquely identifies each row in a table. It ensures that each row in a table is unique and not null. Only one primary key can be defined for a table.
   - **Foreign Key**: A foreign key is a column or a set of columns in one table that references the primary key columns in another table. It establishes a link between the two tables, enforcing referential integrity.

Q6. 
   import mysql.connector

   # Connect to MySQL database
   mydb = mysql.connector.connect(
       host="localhost",
       user="yourusername",
       password="yourpassword",
       database="yourdatabase"
   )

   # Create cursor object
   mycursor = mydb.cursor()

   # Execute SQL query
   mycursor.execute("SELECT * FROM employees")

   # Fetch results
   for row in mycursor.fetchall():
       print(row)

   # Close connection
   mydb.close()
   ```
   - **cursor()**: The cursor() method creates a cursor object which is used to execute SQL queries and fetch results from the database.
   - **execute()**: The execute() method is used to execute SQL queries. It takes an SQL query as a parameter and executes it on the database.

Q7. 
   - 1. **FROM**: Specifies the tables from which to retrieve data.
   - 2. **WHERE**: Filters the rows returned based on a condition.
   - 3. **GROUP BY**: Groups rows that have the same values into summary rows.
   - 4. **HAVING**: Filters groups based on a condition.
   - 5. **SELECT**: Selects the columns to be retrieved.
   - 6. **ORDER BY**: Sorts the result set in ascending or descending order.
   - 7. **LIMIT**: Specifies a limit on the number of rows returned.